<?php

/**
 * @file
 * Tubular is a jQuery plugin that lets you set a YouTube video as your page background
 */

/**
 * Implements hook_init().
 */
function tubular_init() {
  if (tubular_is_enabled()) {
    drupal_add_js(tubular_swfobject_js_path());
    drupal_add_js(tubular_js_path());
    drupal_add_js(array(
      'tubular' => array(
        'videoID' => variable_get('tubular_video_id', ''),
        'wrapperID' => variable_get('tubular_wrapper_id', ''),
      ),
    ), 'setting');
    drupal_add_js(drupal_get_path('module', 'tubular') . '/tubular.js');
  }
}

/**
 * Implements hook_menu().
 */
function tubular_menu() {
  $items = array();
  
  $items['admin/config/user-interface/tubular'] = array(
    'title' => 'Tubular',
    'description' => 'Configuration for Tubular plugin',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('tubular_admin_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'tubular.admin.inc',
  );
  
  return $items;
}

/**
 * Implements hook_theme().
 */
function tubular_theme() {
  return array(
    'tubular_buttons' => array(
      'variables' => array('buttons' => NULL),
      'file' => 'tubular.pages.inc',
    ),
    'tubular_button' => array(
      'variables' => array('button' => NULL),
      'file' => 'tubular.pages.inc',
    ),
  );
}

/**
 * Implements hook_page_alter().
 */
function tubular_page_alter(&$page) {
  if (tubular_is_enabled()) {
    $page['page_bottom']['tubular'] = array(
        '#type' => 'markup',
        '#markup' => theme('tubular_buttons', array('buttons' => tubular_get_buttons())),
    );
  }
}

/**
 * Determines if tubular is properly configured and enabled on the current path
 *
 * @return boolean
 *  TRUE if tubular is enabled on the current path
 */
function tubular_is_enabled() {
  return (drupal_match_path(current_path(), variable_get('tubular_pages'))
    && variable_get('tubular_video_id', '') != ''
    && variable_get('tubular_wrapper_id', '') != '');
}

function tubular_buttons() {
  return array(
    'pause' => array(
      'title' => t('Play/Pause'),
      'cssId' => 'videoPause',
    ),
    'stop' => array(
      'title' => t('Stop'),
      'cssId' => 'videoStop',
    ),
    'mute' => array(
      'title' => t('Mute'),
      'cssId' => 'videoMute',
    ),
  );
}

function tubular_buttons_options() {
  $options = array();
  foreach (tubular_buttons() as $key => $button) {
    $options[$key] = $button['title'];
  }
  return $options;
}

function tubular_get_buttons() {
  $buttons = tubular_buttons();
  $active_buttons = array();
  
  foreach (variable_get('tubular_buttons', array()) as $key) {
    if (isset($buttons[$key])) {
      $active_buttons[$key] = $buttons[$key];
    }
  }
  
  return $active_buttons;
}

/**
 * Returns the path to the Tubular JavaScript file.
 *
 * @return mixed
 *   The path to the JavaScript file or FALSE if no file could be found.
 */
function tubular_js_path() {
  $path = libraries_get_path('tubular');

  if (file_exists($path . '/js/jquery.tubular.js')) {
    return $path . '/js/jquery.tubular.js';
  }

  return FALSE;
}

/**
 * Returns the path to the swfobject JavaScript file.
 *
 * @return mixed
 *   The path to the JavaScript file or FALSE if no file could be found.
 */
function tubular_swfobject_js_path() {
  $path = libraries_get_path('swfobject');

  if (file_exists($path . '/swfobject.js')) {
    return $path . '/swfobject.js';
  }

  return FALSE;
}